Models/ErrorViewModel.cs
namespace la_mia_pizzeria_static.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/HomeController.cs
using la_mia_pizzeria_static.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace la_mia_pizzeria_static.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/RazorController.cs
using Microsoft.AspNetCore.Mvc;

namespace la_mia_pizzeria_static.Controllers
{
    public class RazorController : Controller
    {
        public IActionResult Snacks()
        {
            return View();
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Benvenuti a Domino's!!</h1>
</div>

<div>
    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Nome</th>
                <th scope="col">Descrizione</th>
                <th scope="col">Foto</th>
                <th scope="col">Prezzo</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <th scope="row">1</th>
                <td>Margherita</td>
                <td>
                    Lorem Ipsum is simply dummy text of the printing and                        Lorem Ipsum is simply dummy text of the printing and                      typesetting industry. Lorem Ipsum has been the                           industry's standard dummy text ever since the 1500s, when                    an unknown printer took a galley of type and scrambled                      it to make a type specimen book. It has survived not                    only five centuries, but also the leap into electronic                      typesetting, remaining essentially unchanged. It was                        popularised in the 1960s with the release of Letraset                       sheets containing Lorem Ipsum passages, and more                          recently with desktop publishing software like Aldus                      PageMaker including versions of Lorem Ipsum.
                </td>
                <td><img src="/images/pizza_food_example.jpg" alt="foto pizza" width="250" height="300" /> </td>
                <td>5,00 &euro;</td>
            </tr>
            <tr>
                <th scope="row">2</th>
                <td>Capricciosa</td>
                <td>Lorem Ipsum is simply dummy text of the printing and                        Lorem Ipsum is simply dummy text of the printing and                      typesetting industry. Lorem Ipsum has been the                           industry's standard dummy text ever since the 1500s, when                    an unknown printer took a galley of type and scrambled                      it to make a type specimen book. It has survived not                    only five centuries, but also the leap into electronic                      typesetting, remaining essentially unchanged. It was                        popularised in the 1960s with the release of Letraset                       sheets containing Lorem Ipsum passages, and more                          recently with desktop publishing software like Aldus                      PageMaker including versions of Lorem Ipsum.</td>
                <td><img src="/images/pizza_food_example.jpg" alt="foto pizza" width="250" height="300" /></td>
                <td>7,50 &euro;</td>
            </tr>
            <tr>
                <th scope="row">3</th>
                <td>Bufala</td>
                <td>Lorem Ipsum is simply dummy text of the printing and                        Lorem Ipsum is simply dummy text of the printing and                      typesetting industry. Lorem Ipsum has been the                           industry's standard dummy text ever since the 1500s, when                    an unknown printer took a galley of type and scrambled                      it to make a type specimen book. It has survived not                    only five centuries, but also the leap into electronic                      typesetting, remaining essentially unchanged. It was                        popularised in the 1960s with the release of Letraset                       sheets containing Lorem Ipsum passages, and more                          recently with desktop publishing software like Aldus                      PageMaker including versions of Lorem Ipsum.</td>
                <td><img src="/images/pizza_food_example.jpg" alt="foto pizza" width="250" height="300" /></td>
                <td>8,50 &euro;</td>
            </tr>
        </tbody>
    </table>

</div>

Views/Razor/Snacks.cshtml
@{
    Layout = "_SnackLayout";
}

<h1>Pagina degli snacks!</h1>


@*1. Dichiarare una variabile valorizzandola con il nostro nome.
Dichiarare un'altra variabile valorizzandola con il nostro cognome.
Stampare il nostro nome e cognome all'interno di un tag h2.*@

@{
    string nome = "Roberto";
    string surname = "Giacomuzzo";
}
<h2>Benvenuto @nome @surname</h2>
@*
2. Creare una funzione che stampa la somma dei numeri che vanno da 1 a n (con n passato come parametro - n incluso)
Stampare dentro uno span il risultato.*@

@{
    int endNumber = new Random().Next(1, 100);
    int sum = 0;
    for(int i = 0; i <= endNumber; i++){
        sum += i;
    }
}
<span>La somma random di oggi è: @sum</span>

@*3. Contare quante volte la lettera a è presente nalla frase "nel mezzo del cammin di nostra vita" e stampare questo valore in pagina*@

@{
    string stringToCheck = "nel mezzo del cammin di nostra vita";
    string charToCheck = "a";
    int numberOfCharsIntoString = stringToCheck.Split(charToCheck).Length - 1;
}

<div>Nella frase "@stringToCheck" ci stanno @numberOfCharsIntoString "@charToCheck"</div>

@*4. Creare una List<int> di 20 numeri interi (generati random da 1 a 90, 1 e 90 inclusi) e mostrare in pagina solo i numeri compresi tra 20 e 70*@

@{
    List<int> listOfNumbers = new List<int>();
    for(int i = 0; i < 20; i++){
        int randomNumber = new Random().Next(1, 90);
        listOfNumbers.Add(randomNumber);
    }
    foreach (int number in listOfNumbers)
    {
        if (number > 20 && number < 70)
        {
            <span>@number</span>
        }
    }
}

@*5. Stampare in pagina la data e l'ora attuale (usando la classe DateTime) con il formato anno-mese-giorno ore:minuti:secondi
  *@

@{
    DateTime todayDay = DateTime.Now;
}
<div>La data di oggi è: @todayDay.ToString("yyyy/mm/dd")</div>

@*6. Partendo dalla data di oggi (usando la classe DateTime) stampare in pagina
a. la data di 7 giorni fa
b. che giorno della settimana è oggi (il risultato dovrà essere il nome del giorno (Lunedì, Martedì, ...)
c. che giorno della settimana sarà nello stesso giorno e mese di oggi ma tra un anno (il risultato dovrà essere il nome del giorno (Lunedì, Martedì, ...)*@

@{
    todayDay.AddDays(-7.0);
}

<div>La data di una settimana fa è: @todayDay.AddDays(-7.0).ToString("yyyy/mm/dd")</div>
<div>Oggi è: @todayDay.DayOfWeek</div>
<div>Il giorno fra un anno sarà: @todayDay.AddYears(1).DayOfWeek</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - la_mia_pizzeria_static</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/la_mia_pizzeria_static.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">la_mia_pizzeria_static</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Razor" asp-action="Snacks">Snacks</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - la_mia_pizzeria_static - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_SnackLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <div>
        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Torna alla Home</a>
        @RenderBody()
    </div>
</body>
</html>